### PR TITLE
Remove support for deleting user-ids and subkeys. Use revoke* instead.

### PR DESCRIPTION
**Pull request by vanitasvitae**
See #210 

@tomholub @DenBond7 I hope you do not rely on this functionality. Please let me know if you have objections to this, though I learned that deleting should not be used at all in OpenPGP.

### CODE REVIEW

**Comment by tomholub** [comment]
I'm pretty sure we use that, or would like to use that, on server side. I don't think we need it for subkeys, but I'd like to be able to freely manipulate user ids without having to revoke them.

**Comment by vanitasvitae** [comment]
If you really need to delete user-ids from public/secret keys, you can use BC directly:
```
        // SecretKeyRing
        PGPSecretKeyRing secretKeys = ...
        PGPSecretKey secretKey = secretKeys.getSecretKey(); // user-ids are located on primary key only
        PGPPublicKey publicKey = secretKey.getPublicKey(); // user-ids are placed on the public key part
        publicKey = PGPPublicKey.removeCertification(publicKey, "UserId");
        secretKey = PGPSecretKey.replacePublicKey(secretKey, publicKey);
        secretKeys = PGPSecretKeyRing.insertSecretKey(secretKeys, secretKey);

        // PublicKeyRing
        PGPPublicKeyRing publicKeys = ...
        PGPPublicKey publicKey = publicKeys.getPublicKey(); // user-ids are placed on the public key part
        publicKey = PGPPublicKey.removeCertification(publicKey, "UserId");
        publicKeys = PGPPublicKeyRing.insertPublicKey(publicKeys, publicKey);
```

I can add a utility class (with a warning in the javadoc) for this if you want :)

**Comment by tomholub** [comment]
Got it, that will do. I'll link to here from our internal repo as we may bump into this when upgrading.

**Comment by IvanPizhenko** [comment]
Hmm, I'd say we use it and want such functionality to remain. Obviously need utility class for that.

**Comment by vanitasvitae** [comment]
You should really consider (on client side) to switch to revocations instead of deletions.

If you republish a certificate with deleted user-ids/subkeys, the receiving implementation will just merge their old copy of the certificate with the new one, resulting in a certificate containing both the old and new user-ids/subkeys. (Merging certificates is not yet implemented in PGPainless).

Revoked user-ids/subkeys won't be used for encryption etc. anyways, so you can more or less present them to the user in the same fashion as a deleted user-id/subkey.

But yeah, at least for user-ids I added some utility methods and the same can be done for subkeys if you really need them for some reason.

**Comment by IvanPizhenko** [comment]
@vanitasvitae What if we need to do following:
1. Remove user id from keypair - if we do it the way you suggest, revoke it.
2. Later, add same user id to keypair again. (i.e. I assume add one more another signature with the same user id)

Is it possible? Will BC and PGPainless handle such keypair correctly?

**Comment by vanitasvitae** [comment]
Yes. If you soft-revoke the user-id (meaning you specify a revocation reason which allows to re-certify the Id later), you can simply create a new certification at a later point in time, which restores the user-ids validity state.

**Pull request merged**
