### PR TITLE
Simplify handling of cleartext-signed data

### PR DESCRIPTION
**Pull request by vanitasvitae**
This MR further brings handling of cleartext-signed data in line with handling of inband-signed data.
It also gets rid of the ugly hacky `ConsumerOptions.isCleartextSigned()`.

### CODE REVIEW

**Comment by vanitasvitae** [comment]
While after merging this PR, the codebase still passes all tests, we probably want to be on the safe side and create a dedicated alpha release for possible smoke testing in downstream projects.

**Comment by vanitasvitae** [comment]
Created release `1.1.1-alpha1` with just this change compared to `1.1.0`.
The new release should be available on maven central in a few hours.

@DenBond7 @IvanPizhenko @tomholub if you could build your apps using the alpha version of pgpainless to do some smoke testing (maybe you have an extensive test suite that you could run the alpha against to check if something breaks?), that would be awesome!

**Comment by IvanPizhenko** [comment]
@DenBond7 @vanitasvitae I've tried and automated tests for EAP, EKM, FES and WKD passed.
**UPDATE:** Unit tests for Android app have passed.

**Comment by DenBond7** [comment]
@IvanPizhenko @vanitasvitae 
> Unit tests for Android app have passed.

I've checked this moment. All looks good. I have not found any critical issues.

**Pull request merged**
