### PR TITLE
Relax constraints on decryption keys to improve interop with broken producers

### PR DESCRIPTION
**Pull request by vanitasvitae**
Apparently there are broken legacy apps around which erroneously encrypt messages to primary keys not marked as encryption capable (e.g. RSA primary keys with [SC] key flags, see #372).

PGPainless currently takes key-flags into consideration and refuses to decrypt messages using keys that lack encryption keyflags. As a result, messages produced by broken clients fail to decrypt.

This PR relaxes these constraints and limits validity checks on decryption keys to only check if subkeys have been valid at some point and if the public key algorithm they are based on is capable of encryption (no point in trying to decrypt with an ECDSA key).

This comes with the added benefit, that we should be able to decrypt messages using expired or revoked subkeys as well.

Addresses #373

### CODE REVIEW

**Comment by vanitasvitae** [comment]
TODO: Should we add a config flag for this and default to current behaviour?

**Comment by vanitasvitae** [comment]
Obviously, this PR fails this test:
https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/test/java/org/pgpainless/decryption_verification/PreventDecryptionUsingNonEncryptionKeyTest.java#L192

**Comment by sushengloong** [comment]
@vanitasvitae thank you again for your help with [my issue](https://github.com/pgpainless/pgpainless/issues/372) earlier on and for creating this PR so quickly!

Any chance for this to be released soon? Please let me know if there is anything I can help.

**Comment by vanitasvitae** [comment]
I will think a bit more about this patch and decide about it later today or maybe tomorrow.
Then, drafting a release can be done in no time :)

**Pull request merged**
